In [0]:
import numpy as np
import copy
import random

## Part1

In [0]:
s = np.array([1, 1, 1, -1])


In [0]:
def make_weight_matrix(inputs):
  o = 0
  for i in range(len(inputs)):
    m = np.matmul(inputs[i], inputs[i].T) - np.eye(len(inputs[i]), dtype = int)
    o += m
  return o

In [0]:
def make_predictions(input_pattern, weight, activation_function):
  return activation_function(np.matmul(input_pattern.T, weight)).T

In [0]:
def activation_function(x):
  return 2*(x>=0) - 1

In [0]:
s = s.reshape(-1, 1)

In [0]:
weight = make_weight_matrix([s])
prediction = make_predictions(s, weight, activation_function)

In [9]:
print("original pattern s is:")
print(s)
print("predicted pattern for s is:")
print(prediction)

original pattern s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
predicted pattern for s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]


## Part2

In [0]:
s1 = np.array([0, 0, 0, -1])
s1 = s1.reshape(-1, 1)
prediction_s1_out = make_predictions(s1, weight, activation_function)
prediction_s1_in = make_predictions(prediction_s1_out, weight, activation_function)


In [17]:
print("original pattern s is:")
print(s)
print("disturbed pattern for s is:")
print(s1)
print("predicted output pattern for s is:")
print(prediction_s1_out)
print("predicted input pattern for s is:")
print(prediction_s1_in)


original pattern s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
disturbed pattern for s is:
[[ 0]
 [ 0]
 [ 0]
 [-1]]
predicted output pattern for s is:
[[1]
 [1]
 [1]
 [1]]
predicted input pattern for s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]


In [0]:
s2 = np.array([1, 0, 0, 0])
s2 = s2.reshape(-1, 1)
prediction_s2_out = make_predictions(s2, weight, activation_function)
# prediction_s2_in = make_predictions(prediction_s2_out, weight, activation_function)

In [21]:
print("original pattern s is:")
print(s)
print("disturbed pattern for s is:")
print(s2)
print("predicted output pattern for s is:")
print(prediction_s2_out)
# print("predicted input pattern for s is:")
# print(prediction_s2_in)


original pattern s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
disturbed pattern for s is:
[[1]
 [0]
 [0]
 [0]]
predicted output pattern for s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]


In [0]:
s3 = np.array([0, 1, 0, 0])
s3 = s3.reshape(-1, 1)
prediction_s3_out = make_predictions(s3, weight, activation_function)
# prediction_s3_in = make_predictions(prediction_s3_out, weight, activation_function)

In [23]:
print("original pattern s is:")
print(s)
print("disturbed pattern for s is:")
print(s3)
print("predicted output pattern for s is:")
print(prediction_s3_out)
# print("predicted input pattern for s is:")
# print(prediction_s3_in)


original pattern s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
disturbed pattern for s is:
[[0]
 [1]
 [0]
 [0]]
predicted output pattern for s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]


In [0]:
s4 = np.array([0, 0, 1, 0])
s4 = s4.reshape(-1, 1)
prediction_s4_out = make_predictions(s4, weight, activation_function)
# prediction_s4_in = make_predictions(prediction_s4_out, weight, activation_function)

In [25]:
print("original pattern s is:")
print(s)
print("disturbed pattern for s is:")
print(s4)
print("predicted output pattern for s is:")
print(prediction_s4_out)
# print("predicted input pattern for s is:")
# print(prediction_s4_in)


original pattern s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
disturbed pattern for s is:
[[0]
 [0]
 [1]
 [0]]
predicted output pattern for s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]


## Part3

In [0]:
s1 = np.array([-1, -1, -1, -1])
s1 = s1.reshape(-1, 1)
prediction_s1_out = make_predictions(s1, weight, activation_function)
prediction_s1_in = make_predictions(prediction_s1_out, weight, activation_function)


In [27]:
print("original pattern s is:")
print(s)
print("disturbed pattern for s is:")
print(s1)
print("predicted output pattern for s is:")
print(prediction_s1_out)
print("predicted input pattern for s is:")
print(prediction_s1_in)

original pattern s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
disturbed pattern for s is:
[[-1]
 [-1]
 [-1]
 [-1]]
predicted output pattern for s is:
[[-1]
 [-1]
 [-1]
 [ 1]]
predicted input pattern for s is:
[[-1]
 [-1]
 [-1]
 [ 1]]


In [0]:
s2 = np.array([1, -1, -1, 1])
s2 = s2.reshape(-1, 1)
prediction_s2_out = make_predictions(s2, weight, activation_function)
prediction_s2_in = make_predictions(prediction_s2_out, weight, activation_function)

In [31]:
print("original pattern s is:")
print(s)
print("disturbed pattern for s is:")
print(s2)
print("predicted output pattern for s is:")
print(prediction_s2_out)
print("predicted input pattern for s is:")
print(prediction_s2_in)


original pattern s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
disturbed pattern for s is:
[[ 1]
 [-1]
 [-1]
 [ 1]]
predicted output pattern for s is:
[[-1]
 [-1]
 [-1]
 [ 1]]
predicted input pattern for s is:
[[-1]
 [-1]
 [-1]
 [ 1]]


In [0]:
s3 = np.array([-1, 1, -1, 1])
s3 = s3.reshape(-1, 1)
prediction_s3_out = make_predictions(s3, weight, activation_function)
prediction_s3_in = make_predictions(prediction_s3_out, weight, activation_function)

In [35]:
print("original pattern s is:")
print(s)
print("disturbed pattern for s is:")
print(s3)
print("predicted output pattern for s is:")
print(prediction_s3_out)
print("predicted input pattern for s is:")
print(prediction_s3_in)

original pattern s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
disturbed pattern for s is:
[[-1]
 [ 1]
 [-1]
 [ 1]]
predicted output pattern for s is:
[[-1]
 [-1]
 [-1]
 [ 1]]
predicted input pattern for s is:
[[-1]
 [-1]
 [-1]
 [ 1]]


In [0]:
s4 = np.array([-1, -1, 1, 1])
s4 = s4.reshape(-1, 1)
prediction_s4_out = make_predictions(s4, weight, activation_function)
prediction_s4_in = make_predictions(prediction_s4_out, weight, activation_function)

In [39]:
print("original pattern s is:")
print(s)
print("disturbed pattern for s is:")
print(s4)
print("predicted output pattern for s is:")
print(prediction_s4_out)
print("predicted input pattern for s is:")
print(prediction_s4_in)


original pattern s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
disturbed pattern for s is:
[[-1]
 [-1]
 [ 1]
 [ 1]]
predicted output pattern for s is:
[[-1]
 [-1]
 [-1]
 [ 1]]
predicted input pattern for s is:
[[-1]
 [-1]
 [-1]
 [ 1]]


## Part4

In [0]:
def a_function(x):
    y = 2*(x>=0) - 1
    y[x == 0] = x[x==0]
    return y

In [0]:
def hopfield_prediction(input_array, index_list,  weight, activation_function):
  copy_input = copy.deepcopy(input_array)
  for i in (index_list):
    prediction = activation_function(np.matmul(copy_input.T, weight) + copy_input.T).T
    copy_input[i] = prediction[i]
    print("output in iteration:")
    print(copy_input)
  return copy_input

For missed data

In [57]:
s1 = np.array([0,0,0,-1])
s1 = s1.reshape(-1, 1)
index_list = [0, 1, 2, 3]
random.shuffle(index_list)
print("index list is: ",index_list)
p_s1 = hopfield_prediction(s1, index_list, weight, a_function)

index list is:  [0, 3, 1, 2]
output in iteration:
[[ 1]
 [ 0]
 [ 0]
 [-1]]
output in iteration:
[[ 1]
 [ 0]
 [ 0]
 [-1]]
output in iteration:
[[ 1]
 [ 1]
 [ 0]
 [-1]]
output in iteration:
[[ 1]
 [ 1]
 [ 1]
 [-1]]


In [58]:
print("original pattern s is:")
print(s)
print("disturbed pattern for s is:")
print(s1)
print("predicted output pattern for s is:")
print(p_s1)

original pattern s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
disturbed pattern for s is:
[[ 0]
 [ 0]
 [ 0]
 [-1]]
predicted output pattern for s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]


In [59]:
s2 = np.array([1, 0, 0, 0])
s2 = s2.reshape(-1, 1)
index_list = [0, 1, 2, 3]
random.shuffle(index_list)
print("index list is: ", index_list)
p_s2 = hopfield_prediction(s2, index_list, weight, a_function)

index list is:  [1, 2, 0, 3]
output in iteration:
[[1]
 [1]
 [0]
 [0]]
output in iteration:
[[1]
 [1]
 [1]
 [0]]
output in iteration:
[[1]
 [1]
 [1]
 [0]]
output in iteration:
[[ 1]
 [ 1]
 [ 1]
 [-1]]


In [60]:
print("original pattern s is:")
print(s)
print("disturbed pattern for s is:")
print(s2)
print("predicted output pattern for s is:")
print(p_s2)

original pattern s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
disturbed pattern for s is:
[[1]
 [0]
 [0]
 [0]]
predicted output pattern for s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]


In [61]:
s3 = np.array([0, 1, 0, 0])
s3 = s3.reshape(-1, 1)
index_list = [0, 1, 2, 3]
random.shuffle(index_list)
print("index list is: ", index_list)
p_s3 = hopfield_prediction(s3, index_list, weight, a_function)

index list is:  [3, 0, 2, 1]
output in iteration:
[[ 0]
 [ 1]
 [ 0]
 [-1]]
output in iteration:
[[ 1]
 [ 1]
 [ 0]
 [-1]]
output in iteration:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
output in iteration:
[[ 1]
 [ 1]
 [ 1]
 [-1]]


In [62]:
print("original pattern s is:")
print(s)
print("disturbed pattern for s is:")
print(s3)
print("predicted output pattern for s is:")
print(p_s3)

original pattern s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
disturbed pattern for s is:
[[0]
 [1]
 [0]
 [0]]
predicted output pattern for s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]


In [65]:
s4 = np.array([0, 0, 1, 0])
s4 = s4.reshape(-1, 1)
index_list = [0, 1, 2, 3]
random.shuffle(index_list)
print("index list is: ", index_list)
p_s4 = hopfield_prediction(s4, index_list, weight, a_function)

index list is:  [1, 2, 0, 3]
output in iteration:
[[0]
 [1]
 [1]
 [0]]
output in iteration:
[[0]
 [1]
 [1]
 [0]]
output in iteration:
[[1]
 [1]
 [1]
 [0]]
output in iteration:
[[ 1]
 [ 1]
 [ 1]
 [-1]]


In [67]:
print("original pattern s is:")
print(s)
print("disturbed pattern for s is:")
print(s4)
print("predicted output pattern for s is:")
print(p_s4)

original pattern s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
disturbed pattern for s is:
[[0]
 [0]
 [1]
 [0]]
predicted output pattern for s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]


For noisy data

In [64]:
s1 = np.array([-1, -1, -1, -1])
s1 = s1.reshape(-1, 1)
index_list = [0, 1, 2, 3]
random.shuffle(index_list)
print("index list is: ",index_list)
p_s1 = hopfield_prediction(s1, index_list, weight, a_function)

index list is:  [2, 0, 3, 1]
output in iteration:
[[-1]
 [-1]
 [-1]
 [-1]]
output in iteration:
[[-1]
 [-1]
 [-1]
 [-1]]
output in iteration:
[[-1]
 [-1]
 [-1]
 [ 1]]
output in iteration:
[[-1]
 [-1]
 [-1]
 [ 1]]


In [68]:
s2 = np.array([1, -1, -1, 1])
s2 = s2.reshape(-1, 1)
index_list = [0, 1, 2, 3]
random.shuffle(index_list)
print("index list is: ", index_list)
p_s2 = hopfield_prediction(s2, index_list, weight, a_function)

index list is:  [3, 2, 0, 1]
output in iteration:
[[ 1]
 [-1]
 [-1]
 [ 1]]
output in iteration:
[[ 1]
 [-1]
 [-1]
 [ 1]]
output in iteration:
[[-1]
 [-1]
 [-1]
 [ 1]]
output in iteration:
[[-1]
 [-1]
 [-1]
 [ 1]]


In [69]:
print("original pattern s is:")
print(s)
print("disturbed pattern for s is:")
print(s2)
print("predicted output pattern for s is:")
print(p_s2)

original pattern s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
disturbed pattern for s is:
[[ 1]
 [-1]
 [-1]
 [ 1]]
predicted output pattern for s is:
[[-1]
 [-1]
 [-1]
 [ 1]]


In [70]:
s3 = np.array([-1, 1, -1, 1])
s3 = s3.reshape(-1, 1)
index_list = [0, 1, 2, 3]
random.shuffle(index_list)
print("index list is: ", index_list)
p_s3 = hopfield_prediction(s3, index_list, weight, a_function)

index list is:  [2, 3, 1, 0]
output in iteration:
[[-1]
 [ 1]
 [-1]
 [ 1]]
output in iteration:
[[-1]
 [ 1]
 [-1]
 [ 1]]
output in iteration:
[[-1]
 [-1]
 [-1]
 [ 1]]
output in iteration:
[[-1]
 [-1]
 [-1]
 [ 1]]


In [71]:
print("original pattern s is:")
print(s)
print("disturbed pattern for s is:")
print(s3)
print("predicted output pattern for s is:")
print(p_s3)

original pattern s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
disturbed pattern for s is:
[[-1]
 [ 1]
 [-1]
 [ 1]]
predicted output pattern for s is:
[[-1]
 [-1]
 [-1]
 [ 1]]


In [72]:
s4 = np.array([-1, -1, 1, 1])
s4 = s4.reshape(-1, 1)
index_list = [0, 1, 2, 3]
random.shuffle(index_list)
print("index list is: ", index_list)
p_s4 = hopfield_prediction(s4, index_list, weight, a_function)

index list is:  [0, 2, 3, 1]
output in iteration:
[[-1]
 [-1]
 [ 1]
 [ 1]]
output in iteration:
[[-1]
 [-1]
 [-1]
 [ 1]]
output in iteration:
[[-1]
 [-1]
 [-1]
 [ 1]]
output in iteration:
[[-1]
 [-1]
 [-1]
 [ 1]]


In [73]:
print("original pattern s is:")
print(s)
print("disturbed pattern for s is:")
print(s4)
print("predicted output pattern for s is:")
print(p_s4)

original pattern s is:
[[ 1]
 [ 1]
 [ 1]
 [-1]]
disturbed pattern for s is:
[[-1]
 [-1]
 [ 1]
 [ 1]]
predicted output pattern for s is:
[[-1]
 [-1]
 [-1]
 [ 1]]
