In [0]:
import numpy as np

## Part1

In [0]:
s = np.array([1, 1, 1, -1])

In [0]:
def make_weight_matrix(inputs):
  o = 0
  for i in range(len(inputs)):
    m = np.matmul(inputs[i], inputs[i].T) - np.eye(len(inputs[i]), dtype = int)
    o += m
  return o

In [0]:
def make_predictions(input_pattern, weight, activation_function):
  return activation_function(np.matmul(input_pattern.T, weight)).T

In [0]:
def activation_function(x):
  return 2*(x>=0) - 1

In [0]:
s = s.reshape(-1, 1)
weight = make_weight_matrix([s])

In [0]:
prediction = make_predictions(s, weight, activation_function)

In [0]:
print("original pattern is: ")
print(s)
print("predicted pattern is: ")
print(prediction)

original pattern is: 
[[ 1]
 [ 1]
 [ 1]
 [-1]]
predicted pattern is: 
[[ 1]
 [ 1]
 [ 1]
 [-1]]


## Part2

In [0]:
a = np.array([-1, 1, 1, 1])
a = a.reshape(-1, 1)

In [0]:
weight2 = make_weight_matrix([s, a])

In [0]:
prediction_s = make_predictions(s, weight2, activation_function)
prediction_a = make_predictions(a, weight2, activation_function)

In [0]:
print("original pattern for s is: ")
print(s)
print("predicted pattern for s is: ")
print(prediction_s)

original pattern for s is: 
[[ 1]
 [ 1]
 [ 1]
 [-1]]
predicted pattern for s is: 
[[ 1]
 [ 1]
 [ 1]
 [-1]]


In [0]:
print("original pattern for a is: ")
print(a)
print("predicted pattern for a is: ")
print(prediction_a)

original pattern for a is: 
[[-1]
 [ 1]
 [ 1]
 [ 1]]
predicted pattern for a is: 
[[-1]
 [ 1]
 [ 1]
 [ 1]]


## Part3

In [0]:
b = np.array([1, -1, 1, 1])
b = b.reshape(-1, 1)

In [0]:
weight3 = make_weight_matrix([s, a, b])

In [0]:
prediction_s = make_predictions(s, weight3, activation_function)
prediction_a = make_predictions(a, weight3, activation_function)
prediction_b = make_predictions(b, weight3, activation_function)


In [0]:
print("original pattern for s is: ")
print(s)
print("predicted pattern for s is: ")
print(prediction_s)

original pattern for s is: 
[[ 1]
 [ 1]
 [ 1]
 [-1]]
predicted pattern for s is: 
[[ 1]
 [ 1]
 [ 1]
 [-1]]


In [0]:
print("original pattern for a is: ")
print(a)
print("predicted pattern for a is: ")
print(prediction_a)

original pattern for a is: 
[[-1]
 [ 1]
 [ 1]
 [ 1]]
predicted pattern for a is: 
[[-1]
 [ 1]
 [ 1]
 [ 1]]


In [0]:
print("original pattern for b is: ")
print(b)
print("predicted pattern for b is: ")
print(prediction_b)

original pattern for b is: 
[[ 1]
 [-1]
 [ 1]
 [ 1]]
predicted pattern for b is: 
[[ 1]
 [-1]
 [ 1]
 [ 1]]


## Part4

In [0]:
c = np.array([1, 1, -1, 1])

In [0]:
c = c.reshape(-1, 1)

In [0]:
weight4 = make_weight_matrix([s, a, b, c])

In [0]:
prediction_s = make_predictions(s, weight4, activation_function)
prediction_a = make_predictions(a, weight4, activation_function)
prediction_b = make_predictions(b, weight4, activation_function)
prediction_c = make_predictions(c, weight4, activation_function)


In [0]:
print("original pattern for s is: ")
print(s)
print("predicted pattern for s is: ")
print(prediction_s)

original pattern for s is: 
[[ 1]
 [ 1]
 [ 1]
 [-1]]
predicted pattern for s is: 
[[1]
 [1]
 [1]
 [1]]


In [0]:
print("original pattern for a is: ")
print(a)
print("predicted pattern for a is: ")
print(prediction_a)

original pattern for a is: 
[[-1]
 [ 1]
 [ 1]
 [ 1]]
predicted pattern for a is: 
[[1]
 [1]
 [1]
 [1]]


In [0]:
print("original pattern for b is: ")
print(b)
print("predicted pattern for b is: ")
print(prediction_b)

original pattern for b is: 
[[ 1]
 [-1]
 [ 1]
 [ 1]]
predicted pattern for b is: 
[[1]
 [1]
 [1]
 [1]]


In [0]:
print("original pattern for c is: ")
print(c)
print("predicted pattern for c is: ")
print(prediction_c)

original pattern for c is: 
[[ 1]
 [ 1]
 [-1]
 [ 1]]
predicted pattern for c is: 
[[1]
 [1]
 [1]
 [1]]
